export const excludePatterns = [
    // ✅ 리스트/카테고리 문서
    "List of ",
    "Lists of ",
    "Index of ",
    "Outline of ",
    "History of ",
    "Geography of ",
    "Category:Categories by ",
    "Municipalities of ",
    "Communities of ",
    "Former populated places in ",
    "Mountain resorts in ",
    "Populated places in ",
    "Cities and towns in ",
    "Cities in ",
    "Villages in ",
    "Towns and villages in ",
    "Villages of ",
    "Port cities and towns in ",
    "Populated coastal places in ",
    "Wikipedia categories named after populated places in ",
    "Yazidi communities in ",
    "Kurdish villages in ",
    "Categories by city in ",
    "Neighborhoods of ",
    "Template:",
    "Metropolitan areas of ",
    "Coastal cities in ",
    "Images of cities in ",
    "Flags of cities in ",
    "Capitals of country subdivisions in ",
    "Urban decay in ",
    "Politics by city in ",
    "Canada in fiction by city",
    "Belizean people by populated place",
    "Public housing estates in ",
    "Books about cities in ",
    "China in fiction by city",
    "Ancient Chinese cities",

    // ✅ 중국 관련 (특수)
    "Sub-prefectural city",
    "Sub-provincial cities",
    "Chinese City Creativity Index",
    "Former cities in ",
    "Lists by city in ",
    "Provincial capitals in ",
    "Provincial-controlled division",
    "Town-level city",
    "Special administrative regions of ",

    // ✅ 인도네시아 관련
    "City status in ",
    "Central business districts in ",

    // ✅ 행정 구역
    "Capital of ",
    "District",
    "Province",
    "Region",
    "Governorate",
    "Prefecture",
    "Oblast",
    "Canton",
    "County",
    "Parish",
    "Municipality",
    "Administrative divisions of ",
    "Subdivisions of ",
    "Departments of ",
    "States of ",
    "Territories of ",
    "Autonomous ",
    "neighborhood",
    "Quarter",
    "Area",
    "Planned communities in ",

    // ✅ 시설/명소
    "Monastery",
    "Fortress",
    "Castle",
    "Airport",
    "Railway station",
    "University",
    "Stadium",
    "National Park",
    "Nature Reserve",
    "Biosphere Reserve",
    "UNESCO",
    "Heritage Site",
    "Cemetery",
    "Hospital",
    "Replica constructions in ",

    // ✅ 기타
    "Metropolitan",
    "Agglomeration",
    "Islands of ",
    "Suburbs of ",
    "National Civilized City",
    "National Famous Historical and Cultural City",
    "National forest cities in ",
    "National Sanitary City",
    "Walled villages of ",
    "people by populated place",
    "capital cities",
    "Suburbs in ",

    // ✅ 새롭게 추가된 패턴
    "Village Community in ",        // Cameroon 예시
    "Refugee camps in ",            // Cameroon 예시
    "Neighbourhoods in ",           // 여러 나라에서 등장
    "Mayors of places in ",         // 보스니아 예시
    "Urban-type settlements in ",   // 벨라루스 예시
    "Populated places on the ",     // 벨라루스 예시
    "Historic Jewish communities in ",
    "Agrotowns in ",                // 벨라루스 예시
    "Set index articles on populated places in ",
    "Municipal coats of arms in ",  // 키프로스 예시
    "Municipal seats of ",          // 덴마크 예시
    "Holocaust locations in ",      // 오스트리아/에스토니아/벨라루스 예시
    "Mining communities in ",       // 핀란드/그리스 예시
    "Fictional populated places in ",
    "Urban planning in ",           // 프랑스 예시
    "Subprefectures in ",           // 프랑스 예시
    "City councils in ",            // 이란 예시
    "Caye",                         // Belize 섬들
    "Circuit",                      // Bushy Park Circuit (바베이도스)
    "Village",                      // Beba Village Community 등 대응
    "Islands",                      // Hawar Islands, Long Island 등
    // ✅ 새로 발견된 패턴들
    "municipality",
    "New City",
    "Valley",
    "Kampong",
    "Islands",
    "cities during the Middle Ages",
    "Statutory city",
    "Spa towns in ",
    "Names of .* places in other languages",
    "metropolitan area",
    "Settlement",
    "Populated waterside places in ",
    "state capitals",
    "city-states",
    "settlements in ",
    "Forest villages",
    "regional capitals",
    "Populated places by regional unit in ",
    "Towns in ",
    "Circuit",
    "Caye",
    "Populated places on the .* River",
    "Municipal councils in ",
    "people by populated place",
    "Suburbs in ",
    "Village",
    // ✅ 일본 관련
    "Cities designated by government ordinance of Japan",
    "Cities of Japan",
    "Core cities of Japan",
    "Special cities of Japan",
    "Environmental model city",
    "Environmental model cities",
    "Tokyo Proper",
    "Former capitals of Japan",
    "Wards of cities in Japan",
    "Kansai Science City",
    "Industrial City of ",
    "Potash City",
    "Druze communities in ",
    "Roman towns and cities in ",
    "Hill stations in ",
    "Township capitals of ",
    "Townships of ",
    "Hill stations in ",
    "Township capitals of ",
    "Townships of ",
    "Capitals of Pakistan",
    "Capitals in Palestine",
    "Industrial City",
    "city templates",
    "Former capitals of ",
    "Neighborhoods in Israel",
    "Kuwait city templates",
    "South Korea city templates",
    "Alawite communities in ",
    "Christian cities in ",
    "Christian communities in ",
    "Palestinian refugee camps in ",
    "Shia Muslim communities in ",
    "Sunni Muslim communities in ",
    "Sucos of ",
    "Administrative posts of ",
    "Edge cities in ",
    "Urban society in ",
    "Refugee Camp",
    "Populated lakeshore places in ",
    "Zongo settlements",
    "Communities in ",
    "Fishing communities in ",
    "Municipalities in ",
    "Local authorities of ",
    "Real estate in ",
    "Histories of cities in ",
    "State capitals in ",
    "Diocese of ",
    "Industrial Park",
    "Industrial and Business Park",
    "Division",
    "Subcounty",
    "Estates",
    "Ministry of ",
    "Mine",
    "Mission",
    "Names of .* places in other languages",
    "Populated places of Arctic ",
    "Urban areas in ",
    "City with county rights",
    "Cities with county rights of ",
    "Frazioni of ",
    "Communes of ",
    "Former Jewish agricultural colonies of ",
    "Populated places under .* control",
    "Boroughs of ",
    "Company towns in ",
    "Monotowns in ",
    "Populated places of Arctic ",
    "Temporary populated places in ",
    "Classification of inhabited localities in ",
    "Shift settlement",
    "Rural localities in ",
    "Volga German settlements",
    "Neighborhoods in ",
    "Old Believer communities in ",
    "Road-inaccessible communities of ",
    "Localities of ",
    "Topographic Relations of ",
    "Buildings and structures in .* by city",
    "Sport in .* by populated place",
    "Municipal seat",
    "Municipal seats in ",
    "Capitals of states of ",
    "Ski areas and resorts in ",
    "Capitals of .* provinces",
    "Capitals of .* regions",
    "Hamlets in ",
    "Ports and harbours of ",
    "Municipal seat",
    "cities by topic",
    "Populated places of the .* Confederation",
    "Indigenous villages in ",
    "City Special Project",
];